### PR TITLE
Increase /var to >=80Gb free to meet installation requirement

### PR DESCRIPTION
**Pull request by gavindidrichsen**
The main fixes in this PR are to satisfy [hardware requirements](https://docs.chef.io/install_chef_automate.html#hardware-requirements) on the chefautomate server:  RAM must be >= 16Gb, /var must have >= 80Gb free.  The RAM has been increased now from 8Gb Standard_F4s to 16Gb Standard_DS4_vs and the OS disk size from 30 to 100Gb to meet these requirements.

There are a couple minor changes to the baseUrl (the root of the template repo) variable in this PR as well: baseUrl was extracted as a parameter to ease testing and repointed from Azure's chef-automate-ha repository to Chef-Partner's one.

### CODE REVIEW

**Comment by gavindidrichsen** [comment]
@davymcaleer, @russellseymour, @skpaterson.  Hi all can someone please view and approve this pull request?  Thanks.  Gavin.

**Comment by skpaterson** [comment]
Unrelated to the content of this PR but since this is open source, you might want to take a look at: https://github.com/chef-partners/newcrew/blob/master/version_control.md

**Review by skpaterson — APPROVED** [review]
Changes look good!

**Review by davymcaleer — APPROVED** [review]
Looks good to go

**Pull request merged**
