### PR TITLE
Refactor all backend inline scripts into a single script file

### PR DESCRIPTION
**Pull request by gavindidrichsen**
Signed-off-by: Gavin Didrichsen <gavin.didrichsen@gmail.com>

### CODE REVIEW

**Review by russellseymour — COMMENTED** [review]
You have removed a few variables which is good, however have you removed ones that are maybe obsolete now?

For example `variables('customData').leaderCustomData`

**Comment by gavindidrichsen** [comment]
Hi Russell.  All of the obsolete ones have been removed.

**Review by skpaterson — APPROVED** [review]
Looks good!  Minor comment for the future  -`chef-backend-install.sh` could be a parameter given it's used a few times.

**Review by russellseymour — APPROVED** [review]
👍

**Comment by gavindidrichsen** [comment]
Thanks.  Stuart.  I've added your comment about parameterizing the "chef-backend-install.sh" to my backlog list of adjustments.

**Pull request merged**
